### ISSUE TITLE
sellPointTriggerInstaller.lua:46: 'then' expected near '!'

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [loki79uk/PlaceableSellPoints#1]
Hello. This is such an error
Error: E:/FARMING_SIMULATOR/mods/FS19_PlaceableSellPoints/sellPointTriggerInstaller.lua:46: 'then' expected near '!'

**Comment by loki79uk** [comment]
Thank you.  You tested it before me!  Obviously I am writing too much C++ and not enough LUA!!

**Comment by Gonimy-Vetrom** [comment]
It works now
